version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: KuaforRandevu.API/Dockerfile
    image: kuafor-randevu-api:latest
    ports:
      - "7295:8080"
    environment:
      - ConnectionStrings__PostgresConnection=Host=db;Port=5432;Database=kuafor;Username=postgres;Password=Your_password;
      - Redis__Configuration=redis:6379
      - Redis__InstanceName=KuaforRandevu_
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kuafor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Your_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kuafor"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
